// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Bouclier",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .executable(name: "Bouclier", targets: ["Bouclier"]),
        .executable(name: "bouclier-ai-mcp-wrapper", targets: ["MCPWrapper"]),
        // Named "bouclier-cli", not "bouclier": on case-insensitive
        // filesystems (default macOS/APFS) a product named "bouclier"
        // collides with the "Bouclier" app product above — cp/codesign
        // silently overwrite one with the other and the shipped app
        // executable ends up being the CLI. The public command is still
        // `bouclier`, created by the install-time symlink (see
        // CLICore.installCmd), not by this product's build name.
        .executable(name: "bouclier-cli", targets: ["BouclierCLI"]),
    ],
    dependencies: [
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.0.0"),
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.76.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.29.0"),
        .package(url: "https://github.com/apple/swift-nio-transport-services.git", from: "1.23.0"),
        .package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.6.0"),
        .package(url: "https://github.com/huggingface/swift-transformers.git", from: "0.1.12"),
        // ViewInspector lets us assert on SwiftUI view trees without
        // launching a GUI — CI-friendly and catches view-level regressions
        // (missing buttons, wrong copy, broken bindings) that pure unit
        // tests can't see.
        .package(url: "https://github.com/nalexn/ViewInspector.git", from: "0.10.0"),
    ],
    targets: [
        .executableTarget(
            name: "Bouclier",
            dependencies: [
                "BouclierCore",
                .product(name: "GRDB", package: "GRDB.swift"),
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOTLS", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "NIOTransportServices", package: "swift-nio-transport-services"),
                .product(name: "Sparkle", package: "Sparkle"),
                .product(name: "Transformers", package: "swift-transformers"),
            ],
            resources: [
                .copy("Resources"),
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "MCPWrapper",
            dependencies: ["BouclierCore"],
            path: "Sources/MCPWrapper",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .target(
            name: "BouclierCore",
            dependencies: [],
            path: "Sources/BouclierCore",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "BouclierCLI",
            dependencies: ["BouclierCore"],
            path: "Sources/BouclierCLI",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .testTarget(
            name: "BouclierTests",
            dependencies: [
                "Bouclier",
                "BouclierCore",
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOEmbedded", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "ViewInspector", package: "ViewInspector"),
            ],
            resources: [
                // Synthetic media fixtures generated by
                // scripts/generate-test-fixtures.py. Checked in so CI
                // and contributors don't need the Python venv to run
                // the Swift test suite.
                .copy("Fixtures"),
            ]
        ),
    ]
)
