// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Bouclier",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .executable(name: "Bouclier", targets: ["Bouclier"]),
        .executable(name: "bouclier-ai-mcp-wrapper", targets: ["MCPWrapper"]),
        .executable(name: "bouclier-ai-env", targets: ["EnvHelper"]),
        .executable(name: "bouclier-ai-secrets-mcp", targets: ["SecretsMCP"]),
        .executable(name: "bouclier", targets: ["BouclierCLI"]),
    ],
    dependencies: [
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.0.0"),
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.76.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.29.0"),
        .package(url: "https://github.com/apple/swift-nio-transport-services.git", from: "1.23.0"),
        .package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.6.0"),
        .package(url: "https://github.com/huggingface/swift-transformers.git", from: "0.1.12"),
        // ViewInspector lets us assert on SwiftUI view trees without
        // launching a GUI — CI-friendly and catches view-level regressions
        // (missing buttons, wrong copy, broken bindings) that pure unit
        // tests can't see.
        .package(url: "https://github.com/nalexn/ViewInspector.git", from: "0.10.0"),
    ],
    targets: [
        .executableTarget(
            name: "Bouclier",
            dependencies: [
                "BouclierSecretsCore",
                .product(name: "GRDB", package: "GRDB.swift"),
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOTLS", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "NIOTransportServices", package: "swift-nio-transport-services"),
                .product(name: "Sparkle", package: "Sparkle"),
                .product(name: "Transformers", package: "swift-transformers"),
            ],
            resources: [
                .copy("Resources"),
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "MCPWrapper",
            dependencies: [],
            path: "Sources/MCPWrapper",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .target(
            name: "BouclierSecretsCore",
            dependencies: [],
            path: "Sources/BouclierSecretsCore",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "EnvHelper",
            dependencies: ["BouclierSecretsCore"],
            path: "Sources/EnvHelper",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "SecretsMCP",
            dependencies: ["BouclierSecretsCore"],
            path: "Sources/SecretsMCP",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .executableTarget(
            name: "BouclierCLI",
            dependencies: ["BouclierSecretsCore"],
            path: "Sources/BouclierCLI",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .testTarget(
            name: "BouclierTests",
            dependencies: [
                "Bouclier",
                "BouclierSecretsCore",
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOEmbedded", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "ViewInspector", package: "ViewInspector"),
            ],
            resources: [
                // Synthetic media fixtures generated by
                // scripts/generate-test-fixtures.py. Checked in so CI
                // and contributors don't need the Python venv to run
                // the Swift test suite.
                .copy("Fixtures"),
            ]
        ),
    ]
)
